from cronkite.instructions.generate_story import (
    BASE_PREAMBLE,
    FILTER_NOISE_COMPONENT,
    GROUP_ARTICLES_COMPONENT,
    GENERATE_TITLE_COMPONENT,
    GENERATE_SUMMARY_COMPONENT,
    GENERATE_KEY_POINTS_COMPONENT,
    EXTRACT_QUOTES_COMPONENT,
)
